# Project
group=com.tristankechlo.random_mob_sizes

# Common
java_version=21
minecraft_version=1.21.5
version_range=[1.21.5,1.21.6)
auto_service_version=1.1.1

# Forge
forge_version=55.0.23
forge_loader_range=[55,)

# Fabric
fabric_version=0.127.1+1.21.5
fabric_loader_min=0.16
fabric_loader_version=0.16.14
fabric_range_min_inclusive=1.21.5
fabric_range_max_exclusive=1.21.6

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.5.80
neoforge_loader_range=[4,)
neoforge_range=[21.5,)

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.5
parchment_version=2025.06.15

# Mod options
mod_name=RandomMobSizes
mod_author=Buecher_wurm
mod_id=random_mob_sizes
mod_version=2.2.2
mod_file_name=randommobsizes

# Other Mods
modmenu_version=14.0.0-rc.2

#GeckoLibVersion - versions may be different
geckolib_mc_version=1.21.5
geckolib_version_fabric=5.1.0
geckolib_version_forge=5.1.0
geckolib_version_neoforge=5.1.0

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
