# Project
group=com.tristankechlo.random_mob_sizes

# Common
java_version=21
minecraft_version=1.21.4
version_range=[1.21.4,1.22)
auto_service_version=1.1.1

# Forge
forge_version=54.0.9
forge_loader_range=[54,)

# Fabric
fabric_version=0.112.2+1.21.4
fabric_loader_min=0.16
fabric_loader_version=0.16.9
fabric_range_min_inclusive=1.21.4
fabric_range_max_exclusive=1.22

# NeoForge
neoforge_version=21.4.38-beta
neoforge_loader_range=[4,)
neoforge_range=[21.4,)

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2024.12.07

# Mod options
mod_name=RandomMobSizes
mod_author=Buecher_wurm
mod_id=random_mob_sizes
mod_version=2.2.2
mod_file_name=randommobsizes

# Other Mods
modmenu_version=13.0.0-beta.1

#GeckoLibVersion - versions may be different
geckolib_mc_version=1.21.4
geckolib_version_fabric=4.8
geckolib_version_forge=4.8
geckolib_version_neoforge=4.8

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
